import fs from 'node:fs';
import path from 'node:path';
const read=(n)=>JSON.parse(fs.readFileSync(`content/${n}.json`,'utf8'));
const assets=read('assets'),sermons=read('sermons'),gallery=read('gallery');
const decodeEntities = (value = '') => String(value).replaceAll('&#8211;', '–').replaceAll('&amp;', '&').replaceAll('&#8217;', '’').replaceAll('&nbsp;', ' ');
const events=read('events').map(event => ({...event, title: decodeEntities(event.title), description: decodeEntities(event.description)}));
const esc=(s='')=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const arrow='<svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="M4 12h15m-6-6 6 6-6 6" stroke="currentColor" stroke-width="1.5"/></svg>';
const image=(id,alt,cls='',eager=false)=>`<img src="${assets[id]}" alt="${esc(alt)}" class="${cls}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
const link=(url,text,cls='text-link')=>`<a class="${cls}" href="${esc(url)}">${text}${arrow}</a>`;
const maps='https://goo.gl/maps/qXR4hJePJZ36FeVdA';
const nav=[['about-us','Our church'],['services','Services'],['sermons','Sermons'],['events','Events'],['gallery','Gallery'],['give','Give']];
const brand=`<a href="/" class="brand" aria-label="City of David Canterbury home">${image('6422','RCCG emblem')}<span>CITY OF DAVID<small>CANTERBURY</small></span></a>`;
function header(slug){return `<a class="skip" href="#main">Skip to content</a><header class="header"><div class="header-inner">${brand}<button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu <span aria-hidden="true">☰</span></button><nav id="navigation" aria-label="Main navigation">${nav.map(([u,t])=>`<a href="/${u}/" ${slug===u?'aria-current="page"':''}>${t}</a>`).join('')}${link('/visit/','Plan your visit','button gold')}</nav></div></header>`}
function footer(){return `<footer><div class="wrap footer-grid"><div>${brand}<p class="footer-tag">Faith. Family. Community.</p></div><div>${nav.slice(0,5).map(([u,t])=>`<a href="/${u}/">${t}</a>`).join('')}</div><div><a href="/give/">Give</a><a href="/build/">Building project</a><a href="/contact-us/">Contact</a></div><div><a href="https://facebook.com/CityofDavidCanterbury">Facebook</a><a href="https://www.instagram.com/cityofdavidcanterbury">Instagram</a><a href="https://www.youtube.com/@CODCanterbury">YouTube</a><a href="https://twitter.com/CodCanterbury">X / Twitter</a></div></div><div class="wrap copyright">© ${new Date().getFullYear()} RCCG City of David Canterbury<span>To be heaven-minded and fruitful citizens of the Kingdom of God.</span></div></footer>`}
function contact(){return `<section class="wrap section contact-section"><div><h2>We would love<br>to meet you.</h2><p>St. John’s Church of England Primary School,<br>Canterbury</p><p><a href="tel:+447961423332">+44 7961 423332</a><br><a href="mailto:office@codcanterburychurch.org">office@codcanterburychurch.org</a></p><div class="actions">${link(maps,'Get directions')}${link('/visit/','Plan your visit')}</div></div><form name="church-contact" method="POST" action="/thank-you/" data-netlify="true" netlify-honeypot="website"><input type="hidden" name="form-name" value="church-contact"><p hidden><label>Leave this empty <input name="website" tabindex="-1" autocomplete="off"></label></p><label for="name">Name</label><input id="name" name="name" autocomplete="name" required maxlength="120"><label for="email">Email</label><input id="email" name="email" type="email" autocomplete="email" required maxlength="254"><label for="message">Message</label><textarea id="message" name="message" rows="3" required maxlength="5000"></textarea><p class="form-note">Your details will be used to respond to your enquiry. Please avoid sharing sensitive information here.</p><button class="button" type="submit">Send message ${arrow}</button></form></section>`}
const pageIntro=(title,desc)=>`<section class="wrap page-intro"><h1>${title}</h1>${desc?`<p>${desc}</p>`:''}</section>`;
const video=(s,cls='')=>`<button class="video ${cls}" data-video="${s.id}" aria-label="Play ${esc(s.title)}"><img src="https://img.youtube.com/vi/${s.id}/hqdefault.jpg" alt="${esc(s.title)}" loading="lazy"><span class="play"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 4v16l13-8z" fill="currentColor"/></svg></span><span class="duration">${s.duration}</span></button>`;
const serviceStrip=`<div class="service-strip"><div class="wrap"><div><small>Sunday worship</small><strong>9am &amp; 11:30am</strong></div><div><small>Find us</small><strong>St. John’s Primary School, Canterbury</strong></div>${link('/visit/','Plan your visit')}</div></div>`;
const heroSlideData=[
  ['6372','A joyful moment at City of David Canterbury'],
  ['6373','Women worshipping at City of David Canterbury'],
  ['6458','The City of David Canterbury church family']
];
const heroSlider=`<section class="hero-slider" data-hero-slider aria-roledescription="carousel" aria-label="Life at City of David Canterbury"><div class="hero-slides">${heroSlideData.map(([id,alt],index)=>`<figure class="hero-slide ${index===0?'is-active':''}" data-hero-slide aria-hidden="${index===0?'false':'true'}">${image(id,alt,'hero-slide-image',index===0)}</figure>`).join('')}</div><div class="hero-wash" aria-hidden="true"></div><div class="hero-slider-copy"><h1>A place to belong.<br>A faith to live.</h1><p>Welcome to RCCG City of David, Canterbury.<br>Growing together in faith, worship and community.</p><div class="actions">${link('/visit/','Join us this Sunday','button gold')}${link('/sermons/','Watch a sermon','hero-watch-link')}</div></div><div class="hero-slider-controls"><button type="button" class="hero-arrow hero-prev" data-hero-prev aria-label="Previous church photograph"><svg viewBox="0 0 42 24" aria-hidden="true"><path d="M12 2 2 12l10 10M3 12h37"/></svg></button><div class="hero-slider-status" aria-label="Slide selection">${heroSlideData.map((_,index)=>`<button type="button" data-hero-dot="${index}" class="hero-dot ${index===0?'is-active':''}" aria-label="Show photograph ${index+1}" aria-current="${index===0?'true':'false'}">0${index+1}</button>`).join('')}<span class="hero-progress" aria-hidden="true"><span></span></span></div><button type="button" class="hero-arrow hero-next" data-hero-next aria-label="Next church photograph"><svg viewBox="0 0 42 24" aria-hidden="true"><path d="m30 2 10 10-10 10M39 12H2"/></svg></button></div></section>`;
const eventList=(limit=6)=>`<div class="event-list" data-limit="${limit}">${events.slice(0,limit).map(x=>`<a class="event-row" href="/events/${x.id}/"><time>${new Date(x.start_date.replace(' ','T')+'Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'})}<small>${x.start_date.slice(11,16)}</small></time><h3>${esc(x.title)}</h3>${arrow}</a>`).join('')}</div>`;
const mission=['To make heaven.','To take as many people with us.','To accomplish No. 1 above, holiness will be our lifestyle.','To accomplish No. 2 and 3 above, we will plant churches within five minutes walking distance in every city and town of developing countries and within five minutes driving distance in every city and town of developed countries.','We will pursue these objectives until every nation in the world is reached for the Lord Jesus Christ.'];
const visions=['Preach, Teach & Study','Worship & Pray','Fellowship & Care','Serve & Act','Reach-out & Evangelize'];
const give='https://paymentrequest.natwestpayit.com/reusable-links/39240ff5-d447-453c-8107-12962e4c7811';
const buildGive='https://Givingrequest.natwestpayit.com/reusable-links/2d3f3656-08dc-47eb-b1a2-391615701f3e';
const paypal='https://www.paypal.com/donate?token=2A8Iq4F6INWu6Tv3mT4isi6jJHR2y4k_kaK42v3NCZEQI93GhGzOGGYNj3A8KtApbvFDqhFb6-mD9EoQ';
const channelUrl='https://www.youtube.com/@CODCanterbury';
const pages={};
const ministryPhotos={
  audacious:['5778','5779','5780','5782','5783','5786','5790','5791','5792','5793','5796','5797'],
  youth:['citiyouth-worship-1','citiyouth-dinner-1','citiyouth-dinner-2','citiyouth-worship-2','6030','6031','6032','6036','6038','6039','5833','5836','5854','5859','5901','5905']
};
const ministryConfig={
  audacious:{
    name:'AUDACIOUS', label:'Teen church', description:'A church family for teenagers in Canterbury.', instagram:'https://www.instagram.com/cityofdavidcanterbury/',
    title:'Faith with your whole life.', hero:'5778',
    intro:'A place to show up as you are.',
    introText:'Bring your questions, your story and your full self. We are here to grow in faith, find friendship and walk through life together.',
    invitation:'Come as you are.',
    colour:'audacious',
    features:[['Worship','A space to lift our voices, meet with God and grow in faith together.'],['Real conversations','Honest conversations about faith, life and everything in between.'],['Friendship','A welcoming community of people your age, doing life together in Canterbury.']]
  },
  youth:{
    name:'CITIYOUTHS', label:'Youth church', description:'A church community for young adults in Canterbury.', instagram:'https://www.instagram.com/codcyf_/',
    title:'Find your people. Grow your faith.', hero:'citiyouth-worship-1',
    intro:'Faith has room for your questions.',
    introText:'A place for real friendship, honest faith and a church community that knows life is lived beyond Sunday.',
    invitation:'There is a place for you here.',
    colour:'youth',
    gathering:'Citi Breakfast - every Tuesday at 6am on Zoom (UK time).',
    features:[['Worship','A space to encounter God and grow in faith together.'],['Word','Conversations that help us go deeper and connect faith with everyday life.'],['Community','Genuine friendship, support and a place to belong in Canterbury.']]
  }
};
function ministryHeader(config,slug){return `<a class="skip" href="#main">Skip to content</a><header class="ministry-header"><a href="/" class="ministry-wordmark" aria-label="${config.name} home">${config.name}</a><button class="ministry-menu-toggle" aria-expanded="false" aria-controls="ministry-navigation">Menu <span aria-hidden="true">☰</span></button><nav id="ministry-navigation" aria-label="${config.name} navigation"><a href="/" ${slug===''?'aria-current="page"':''}>Home</a><a href="/gatherings/" ${slug==='gatherings'?'aria-current="page"':''}>Gatherings</a><a href="/gallery/" ${slug==='gallery'?'aria-current="page"':''}>Gallery</a><a href="/contact/" ${slug==='contact'?'aria-current="page"':''}>Contact</a><a href="/contact/" class="ministry-visit">Visit us</a></nav></header>`}
function ministryFooter(config){return `<footer class="ministry-footer"><a href="/" class="ministry-wordmark">${config.name}</a><p>Part of RCCG City of David Canterbury.</p><div><a href="https://rccgcodcanterbury.com/">Main church</a><a href="${config.instagram}" aria-label="${config.name} on Instagram">Instagram</a><a href="mailto:office@codcanterburychurch.org">Contact</a></div></footer>`}
function ministryContact(config){const form=`${config.colour}-contact`;return `<section class="ministry-contact" id="contact"><div><h2>We would love to meet you.</h2><p>Want to find the next gathering, ask a question or bring a friend? Send us a message.</p><p>St. John’s Church of England Primary School<br>Canterbury</p><a href="https://goo.gl/maps/qXR4hJePJZ36FeVdA" class="ministry-button">Get directions ${arrow}</a></div><form name="${form}" method="POST" action="/thank-you/" data-netlify="true" netlify-honeypot="website"><input type="hidden" name="form-name" value="${form}"><p hidden><label>Leave this empty <input name="website" tabindex="-1" autocomplete="off"></label></p><label for="${form}-name">Name</label><input id="${form}-name" name="name" autocomplete="name" required maxlength="120"><label for="${form}-email">Email</label><input id="${form}-email" name="email" type="email" autocomplete="email" required maxlength="254"><label for="${form}-message">Message</label><textarea id="${form}-message" name="message" rows="4" required maxlength="5000"></textarea><button type="submit" class="ministry-button">Send message ${arrow}</button></form></section>`}
function ministryGallery(config){return `<div class="ministry-gallery">${ministryPhotos[config.colour].map((id,index)=>`<button data-gallery="${assets[id]}" aria-label="Open ${config.name} photo ${index+1}">${image(id,`${config.name} church gathering ${index+1}`)}</button>`).join('')}</div>`}
function ministryHome(config){return `<section class="ministry-hero"><div class="ministry-hero-copy"><p class="ministry-label">${config.label}</p><h1>${config.title}</h1><p>${config.description}</p><div class="ministry-actions"><a href="/contact/" class="ministry-button">Plan your visit ${arrow}</a><a href="/gallery/" class="ministry-link">See the gallery ${arrow}</a></div></div>${image(config.hero,`${config.name} church community`, 'ministry-hero-image',true)}</section><section class="ministry-intro"><div><h2>${config.intro}</h2><p>${config.introText}</p></div>${ministryGallery(config)}</section><section class="ministry-gathering"><div><p class="ministry-label">Gatherings</p><h2>Real people.<br>Meaningful moments.</h2></div><p>We gather for worship, explore God’s Word, share life and do it together. Contact us for the next gathering.</p><a href="/contact/" class="ministry-link">Find the next gathering ${arrow}</a></section><section class="ministry-features"><h2>${config.invitation}</h2>${config.features.map(([title,text])=>`<article><span></span><h3>${title}</h3><p>${text}</p></article>`).join('')}</section><section class="ministry-invite">${image(ministryPhotos[config.colour][2],`${config.name} community`)}<div><h2>Come as you are.</h2><p>${config.description}</p><a href="/contact/" class="ministry-button">Plan your visit ${arrow}</a></div></section>`}
const ministryPages={};
for(const [key,config] of Object.entries(ministryConfig)){
  ministryPages[key]={
    '':{title:config.name,body:ministryHome(config)},
    gatherings:{title:`Gatherings | ${config.name}`,body:`<section class="ministry-page-intro"><p class="ministry-label">${config.label}</p><h1>Gather with us.</h1><p>Our gathering details change from time to time. Send us a message and we will help you find the next one.</p><a href="/contact/" class="ministry-button">Ask about gatherings ${arrow}</a></section><section class="ministry-page-gallery">${ministryGallery(config)}</section>`},
    gallery:{title:`Gallery | ${config.name}`,body:`<section class="ministry-page-intro"><p class="ministry-label">${config.label}</p><h1>Life together.</h1><p>Moments of worship, friendship and community at ${config.name}.</p></section><section class="ministry-page-gallery">${ministryGallery(config)}</section>`},
    contact:{title:`Contact | ${config.name}`,body:ministryContact(config)},
    'thank-you':{title:`Thank you | ${config.name}`,body:`<section class="ministry-page-intro"><h1>Thank you.</h1><p>Your message has been received. We look forward to meeting you.</p><a href="/" class="ministry-button">Back to ${config.name} ${arrow}</a></section>`}
  };
  if (config.gathering) {
    ministryPages[key][''].body = ministryPages[key][''].body.replace('We gather for worship, explore God’s Word, share life and do it together. Contact us for the next gathering.', esc(config.gathering)).replace('Find the next gathering', 'Get in touch');
    ministryPages[key].gatherings.body = ministryPages[key].gatherings.body.replace('Gather with us.', 'Citi Breakfast.').replace('Our gathering details change from time to time. Send us a message and we will help you find the next one.', esc(config.gathering));
  }
}
pages['']={title:'Welcome to church',body:`<section class="hero"><div class="hero-copy"><h1>A place to belong.<br>A faith to live.</h1><p>Welcome to RCCG City of David, Canterbury.<br>Growing together in faith, worship and community.</p><div class="actions">${link('/visit/','Join us this Sunday','button')}${link('/sermons/','Watch a sermon')}</div></div>${image('6168','Members of City of David Canterbury worshipping together','hero-photo',true)}</section>${serviceStrip}<section class="wrap section intro"><h2>More than a Sunday.<br>A family.</h2><div><p>We’re a warm and welcoming church family, passionate about Jesus, committed to biblical teaching and here to walk together in faith, support one another and make a positive difference in our community.</p>${link('/about-us/','Discover our church')}</div></section><section class="wrap section life"><div class="section-heading"><h2>Life together.</h2>${link('/events/','Explore our calendar')}</div><div class="three-columns">${[['6439','Sunday worship','Gather in worship and the Word.','services'],['6373','Bible study','Grow in faith, together.','services#bible-study'],['6372','Connect Friday','Make space for prayer.','services#prayer']].map(([id,t,d,u])=>`<a class="life-item" href="/${u}${u.includes('#')?'':'/'}">${image(id,t+' at City of David')}<h3>${t}</h3><p>${d}</p></a>`).join('')}</div></section><section class="sermon-feature"><div class="wrap two-columns">${video(sermons[0])}<div><span class="eyebrow">Watch &amp; listen</span><h2>A word for your week.</h2><p>Catch up on messages from City of David Canterbury.</p>${link('/sermons/','Explore sermons','button outline')}</div></div></section><section class="wrap section"><div class="section-heading"><h2>Coming together.</h2>${link('/events/','All events')}</div>${eventList(3)}</section><section class="building-band"><div><h2>Building a home.<br>Growing a community.</h2><p>Support the vision for a place where our community can grow, connect and thrive.</p>${link('/build/','Explore the building project','button')}</div>${image('6458','Our church family')}</section>${contact()}`};
pages[''].body=heroSlider+pages[''].body.slice(pages[''].body.indexOf('</section>')+'</section>'.length);
const nextGeneration=`<section class="next-generation"><div class="wrap"><div class="section-heading"><h2>Find your place.</h2><p>Church has a place for every generation.</p></div><div class="next-generation-grid"><a href="https://audacious.rccgcodcanterbury.com/" class="next-generation-card">${image('5778','Audacious teens church gathering')}<span>Teen church</span><h3>Audacious</h3><p>A place to grow in faith and friendship.</p>${arrow}</a><a href="https://youth.rccgcodcanterbury.com/" class="next-generation-card">${image('citiyouth-worship-1','CITIYOUTHS church gathering')}<span>Youth church</span><h3>CITIYOUTHS</h3><p>A place to grow in faith and friendship.</p>${arrow}</a></div></div></section>`;
pages[''].body=pages[''].body.replace('<section class="wrap section life">',`${nextGeneration}<section class="wrap section life">`);
pages['about-us']={title:'Our church',body:`${pageIntro('Faith at the heart.<br>Family all around.','Welcome to RCCG City of David, Canterbury. A church family growing together in the Word, worship and community.')}<div class="wrap wide-photo">${image('6458','City of David Canterbury church family')}</div><section class="wrap section two-columns"><div><h2>Our mission.</h2><ol class="mission">${mission.map(x=>`<li>${x}</li>`).join('')}</ol></div><div><h2>Our vision.</h2><p>To be heaven-minded and fruitful citizens of the Kingdom of God. <span class="muted">Genesis 1:28</span></p>${visions.map((x,i)=>`<div class="vision-row"><span>0${i+1}</span><h3>${esc(x)}</h3></div>`).join('')}</div></section><section class="wrap section top-zero two-columns"><div><span class="eyebrow">Current ministry</span><h2>Pastor Akin Kunlipe.</h2><p class="large">Pastor Akin Kunlipe is the current pastor at City of David Canterbury.</p></div><div><p>Watch Pastor Akin’s recent messages and the latest services from the church on the official City of David Canterbury YouTube channel.</p>${link(channelUrl,'Visit the YouTube channel','button')}</div></section><section class="beliefs section"><div class="wrap"><h2>What we believe.</h2><div class="three-columns"><article><h3>The Bible</h3><p>We believe that the entire scripture, both Old and New Testaments, is written by the inspiration of the Holy Spirit.</p><p>All Scripture is breathed out by God and profitable for teaching, for reproof, for correction, and for training in righteousness, that the man of God may be complete, equipped for every good work.</p><small>2 Timothy 3:16–17</small></article><article><h3>Jesus Christ</h3><p>We believe in Jesus Christ and faith in Him alone brings about salvation.</p><p>Christ died for our sins in accordance with the Scriptures, was buried, and was raised on the third day in accordance with the Scriptures.</p><small>1 Corinthians 15:3–4</small></article><article><h3>The Holy Spirit</h3><p>The Holy Spirit is the third person in the Trinity. He has the same power and the same glory with God the Father and God the Son. He is our comforter in time of trouble, helper in prayer and guide when we are lost.</p><small>2 Corinthians 13:14</small></article></div></div></section>${contact()}`};
pages['services']={title:'Services',body:`${pageIntro('Gather. Worship. Grow.','There is a place for you in our church family. Join us for worship, the Word and prayer.')}<section class="wrap service-detail two-columns">${image('6168','Our congregation worshipping')}<div><h2>Sunday worship.</h2><p class="large">First service · 9am–11am<br>Second service · 11:30am–2pm</p><p>Function Hall, St. John’s Church of England Primary School, Canterbury.</p>${link('/visit/','Plan your visit','button')}<p class="note">Times shown in the church’s event calendar. Please contact us before travelling, as the services page lists a different Sunday time.</p></div></section><section class="wrap section two-columns" id="bible-study"><div><h2>Grow in the Word.</h2><h3>Wednesday Bible study</h3><p>6pm–7:30pm · via Zoom</p><p>Study the Bible with us and grow in faith together. Contact the church for joining details.</p>${link('mailto:office@codcanterburychurch.org?subject=Bible%20study%20joining%20details','Ask for the Zoom details')}</div><div id="prayer"><h2>Make space for prayer.</h2><h3>Connect Friday</h3><p>10pm–11:30pm · as listed in the event calendar.</p><h3>Monthly vigil</h3><p>Last Friday of the month · 9pm, as listed on the services page.</p><p class="note">Please confirm the arrangements with the church before attending.</p>${link('/events/','View the calendar')}</div></section>${contact()}`};
pages['visit']={title:'Plan your visit',body:`${pageIntro('Your Sunday starts here.','Whether you are exploring faith, new to Canterbury or looking for a church family, we would love to welcome you.')}${serviceStrip}<section class="wrap section two-columns"><div><h2>Come as you are.</h2><p>Join our church family for worship, prayer and the Word. If you have questions before your first visit, please get in touch.</p><h3>Where we meet</h3><p>Function Hall<br>St. John’s Church of England Primary School<br>Canterbury</p>${link(maps,'Get directions','button')}<p class="note">The event calendar lists Sunday services at 9am and 11:30am. Another page lists 9:20am. Please confirm your service time with the church before travelling.</p></div><div>${image('6189','Map showing the church meeting location','location-map')}<div class="visit-contact"><h3>A little help before you arrive?</h3><p>Call <a href="tel:+447961423332">+44 7961 423332</a> or email <a href="mailto:office@codcanterburychurch.org">office@codcanterburychurch.org</a> for access, children’s arrangements or any other questions.</p></div></div></section>${contact()}`};
pages['sermons']={title:'Sermons',body:`${pageIntro('A word for your week.','Watch and listen to the latest messages from City of David Canterbury.')}<section class="wrap section top-zero"><div class="section-heading"><label class="search-label">Find a message<input type="search" id="sermon-search" placeholder="Search title or speaker…"></label>${link(channelUrl,'Visit our YouTube channel')}</div><div class="sermon-grid">${sermons.map(s=>`<article class="sermon-card" data-search="${esc(s.title.toLowerCase())}">${video(s)}<h2>${esc(s.title.split('|')[0].trim())}</h2><p>${esc(s.title.split('|').slice(1).join(' · ').trim())}</p>${link('https://www.youtube.com/watch?v='+s.id,'Watch on YouTube')}</article>`).join('')}</div><p id="sermon-empty" hidden>No messages match your search. Try another title or speaker.</p><p class="note">This selection was updated from the church’s official YouTube channel on 4 October 2026. Visit the channel for the full archive and live services.</p></section>`};
pages['events']={title:'Events',body:`${pageIntro('Coming together.','Worship, prayer and fellowship. Find your next gathering.')}<section class="wrap section top-zero"><div class="event-controls"><label>Event type<select id="event-filter"><option value="all">All gatherings</option><option value="sunday">Sunday services</option><option value="friday">Connect Friday</option></select></label><label>From date<input type="date" id="event-date"></label><a class="text-link" href="/events.ics" download>Download calendar ${arrow}</a></div><div id="events-results">${eventList(events.length)}</div><p class="note">Calendar copied from the church website on 4 October 2026. Times are Europe/London. Please contact the church to confirm arrangements. ${link('https://codcanterburychurch.org/events/','Original calendar')}</p></section>`};
pages['gallery']={title:'Gallery',body:`${pageIntro('This is our family.','Moments of worship, joy and life together at City of David Canterbury.')}<section class="wrap section top-zero"><div class="gallery">${(gallery.length?gallery:Object.keys(assets).filter(id=>Number(id)>5700&&Number(id)<6103)).map((id,i)=>`<button class="gallery-item" data-gallery="${assets[id]}" aria-label="Open church gallery photo ${i+1}">${image(id,`City of David Canterbury church gathering, photo ${i+1}`)}</button>`).join('')}</div></section>`};
const bank=(name,num)=>`<dl class="bank"><div><dt>Account name</dt><dd>${name}</dd></div><div><dt>Sort code</dt><dd>60-06-33</dd></div><div><dt>Account number</dt><dd>${num}</dd></div></dl>`;
pages['give']={title:'Give',body:`${pageIntro('Give with a cheerful heart.','Support the life and work of RCCG City of David Canterbury.')}<section class="wrap section top-zero two-columns"><div><blockquote>“You must each decide in your heart how much to give. And don’t give reluctantly or in response to pressure. For God loves a person who gives cheerfully.”<cite>2 Corinthians 9:7</cite></blockquote><div class="actions">${link(give,'Give online','button')}${link(paypal,'Give via PayPal')}</div><p class="note">You’ll continue to the church’s existing payment provider.</p></div><div><h2>Bank transfer.</h2>${bank('RCCG CITY OF DAVID','34478795')}<p>Giving towards the building project?</p>${link('/build/','Visit the building fund')}</div></section>`};
pages['build']={title:'Building project',body:`${pageIntro('Building a home.<br>Growing a community.','A place where the community can grow, connect and thrive.')}<section class="wrap section top-zero two-columns"><div>${image('6319','Building project vision and giving information','poster')}<p class="note">The church’s original building project appeal.</p></div><div><h2>Be part of the vision.</h2><p>Your support changes everything. Help the church create a place for the community to grow.</p><ul class="giving-options"><li>Quick support - one-time donation</li><li>Monthly Direct Debit - sustained giving</li><li>Be a builder - pledge your gift</li></ul>${link(buildGive,'Give to the building project','button')}<p>For monthly giving or a pledge, contact the church to make arrangements.</p><h3>Building fund bank details</h3>${bank('RCCG City of David Canterbury','34930469')}<p class="note">This account is specifically for the building project. General giving uses a separate account.</p></div></section>${contact()}`};
pages['contact-us']={title:'Contact us',body:`${pageIntro('Let’s connect.','We would love to hear from you.')}${contact()}`};
pages['thank-you']={title:'Thank you',body:`${pageIntro('Thank you for getting in touch.','Your message has been submitted. We look forward to connecting with you.')}<section class="wrap section top-zero">${link('/','Back to the homepage','button')}</section>`};
pages['404']={title:'Page not found',body:`${pageIntro('Let’s find your way.','The page you are looking for could not be found.')}<section class="wrap section top-zero">${link('/','Back to the homepage','button')}</section>`};
for(const event of events){const day=new Date(event.start_date.replace(' ','T')+'Z').toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'UTC'});pages[`events/${event.id}`]={title:event.title,body:`${pageIntro(esc(event.title),esc(day))}<section class="wrap section top-zero two-columns"><div><h2>${event.start_date.slice(11,16)}–${event.end_date.slice(11,16)}</h2><p>Europe/London</p><p>${esc(BeautifulText(event.description))}</p><p>Function Hall, St. John’s Church of England Primary School, Canterbury.</p><div class="actions">${link(maps,'Get directions','button')}${link('/events.ics','Download calendar')}</div></div><div><h3>Before you travel</h3><p>Please contact the church to confirm service details and any changes.</p><p><a href="tel:+447961423332">+44 7961 423332</a><br><a href="mailto:office@codcanterburychurch.org">office@codcanterburychurch.org</a></p>${link('/events/','Back to all events')}</div></section>`}}
function BeautifulText(s){return (s||'').replace(/<[^>]*>/g,'').replaceAll('&amp;','&')}
fs.rmSync('dist',{recursive:true,force:true});fs.mkdirSync('dist',{recursive:true});
fs.cpSync('public','dist',{recursive:true});
// Publish derivatives only; originals remain in the source repository.
for(const f of fs.readdirSync('dist/assets'))if(!f.endsWith('.webp'))fs.unlinkSync('dist/assets/'+f);
const origin=process.env.URL||'https://rccgcod.netlify.app';
for(const [slug,page] of Object.entries(pages)){
 const canonical=origin+'/'+(slug?slug+'/':''); const html=`<!doctype html><html lang="en-GB"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(page.title)} | City of David Canterbury</title><meta name="description" content="${esc(page.title)} - RCCG City of David Canterbury. Worship, prayer, community and the Word. Plan your visit, explore sermons and connect with our church family."><meta name="theme-color" content="#173c32"><link rel="icon" href="${assets['6452']}"><link rel="canonical" href="${canonical}"><meta property="og:title" content="${esc(page.title)} | City of David Canterbury"><meta property="og:type" content="website"><meta property="og:image" content="${origin}${assets['6168']}"><meta property="og:url" content="${canonical}"><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script></head><body>${header(slug)}<main id="main">${page.body}</main>${footer()}<dialog id="media-dialog"><button class="dialog-close" aria-label="Close media">Close ✕</button><div id="media-content"></div></dialog></body></html>`;
 const out=slug==='404'?'dist/404.html':path.join('dist',slug,'index.html');fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,html);
}
for(const [ministry, ministrySite] of Object.entries(ministryPages)){
 const config=ministryConfig[ministry]; const ministryOrigin=`https://${ministry}.rccgcodcanterbury.com`;
 for(const [slug,page] of Object.entries(ministrySite)){
  const canonical=`${ministryOrigin}/${slug?`${slug}/`:''}`;
  const html=`<!doctype html><html lang="en-GB"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(page.title)}</title><meta name="description" content="${esc(config.description)} Part of RCCG City of David Canterbury."><meta name="theme-color" content="${ministry==='audacious'?'#0738db':'#07362e'}"><link rel="icon" href="${assets['6452']}"><link rel="canonical" href="${canonical}"><meta property="og:title" content="${esc(page.title)}"><meta property="og:type" content="website"><meta property="og:image" content="${ministryOrigin}${assets[config.hero]}"><meta property="og:url" content="${canonical}"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/ministry.css"><script src="/app.js" defer></script><script src="/ministry.js" defer></script></head><body class="ministry ministry--${ministry}">${ministryHeader(config,slug)}<main id="main">${page.body}</main>${ministryFooter(config)}<dialog id="media-dialog"><button class="dialog-close" aria-label="Close media">Close ✕</button><div id="media-content"></div></dialog></body></html>`;
  const out=path.join('dist',ministry,slug,'index.html');fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,html);
 }
}
fs.writeFileSync('dist/events.json',JSON.stringify(events));
const icsEsc=s=>s.replaceAll('\\','\\\\').replaceAll('\n','\\n').replaceAll(',','\\,').replaceAll(';','\\;');
const icsDate=s=>s.replaceAll('-','').replaceAll(':','').replace(' ','T');
const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//City of David Canterbury//Church Calendar//EN','X-WR-TIMEZONE:Europe/London','BEGIN:VTIMEZONE','TZID:Europe/London','BEGIN:DAYLIGHT','DTSTART:19700329T010000','RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU','TZOFFSETFROM:+0000','TZOFFSETTO:+0100','TZNAME:BST','END:DAYLIGHT','BEGIN:STANDARD','DTSTART:19701025T020000','RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU','TZOFFSETFROM:+0100','TZOFFSETTO:+0000','TZNAME:GMT','END:STANDARD','END:VTIMEZONE',...events.flatMap(e=>['BEGIN:VEVENT',`UID:${e.id}@codcanterburychurch.org`,'DTSTAMP:20261004T100000Z',`DTSTART;TZID=Europe/London:${icsDate(e.start_date)}`,`DTEND;TZID=Europe/London:${icsDate(e.end_date)}`,`SUMMARY:${icsEsc(e.title)}`,'LOCATION:St. John’s Church of England Primary School\, Canterbury','END:VEVENT']),'END:VCALENDAR'].join('\r\n');fs.writeFileSync('dist/events.ics',ics);
const aliases={'join-our-services':'services','join-us':'visit','event-list':'events','our-beliefs':'about-us','our-community':'about-us','our-church':'about-us','get-in-touch':'contact-us'};
const ministryRedirects=Object.keys(ministryPages).flatMap(ministry=>{const host=`https://${ministry}.rccgcodcanterbury.com`;return [`${host}/assets/* /assets/:splat 200!`,`${host}/style.css /style.css 200!`,`${host}/ministry.css /ministry.css 200!`,`${host}/app.js /app.js 200!`,`${host}/ministry.js /ministry.js 200!`,`${host}/* /${ministry}/:splat 200!`]});
const redirects=[...ministryRedirects,...Object.keys(pages).filter(Boolean).map(s=>`/index.php/${s}/ /${s}/ 301`),...Object.entries(aliases).flatMap(([a,b])=>[`/${a}/ /${b}/ 301`,`/index.php/${a}/ /${b}/ 301`]),'/index.php/artist/the-bible/ /services/#bible-study 301','/index.php/artist/place-of-prayer/ /services/#prayer 301','/index.php/event/* /events/ 301','/index.php/series/* /events/ 301'];fs.writeFileSync('dist/_redirects',redirects.join('\n'));
fs.writeFileSync('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);fs.writeFileSync('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${Object.keys(pages).filter(s=>!['404','thank-you'].includes(s)).map(s=>`<url><loc>${origin}/${s?s+'/':''}</loc></url>`).join('')}</urlset>`);
console.log(`Built ${Object.keys(pages).length} pages, ${events.length} events, ${sermons.length} sermons.`);
